version: "3"

services:
  app:
    build: .
    ports:
      - "80:8080"
    env_file:
      - .env
    depends_on:
      - mosquitto
      - mongo_db
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"


